import { describe, expect, it } from 'bun:test';
import {
  Center, newCompositor, newLayer, newRange, newStyle, newWrapWriter, normalBorder,
  resetHyperlink, setHyperlink, styleRanges, truncate, wrap,
} from '../src/index.js';
import goldens from './fixtures/hyperlink-v2.0.6.json';

// Goldens generated by a real Go program against charm.land/lipgloss/v2@v2.0.6
// and github.com/charmbracelet/x/ansi@v0.11.8, covering every path that emits
// or re-emits OSC 8 hyperlinks, for input links terminated by both ST (ESC \)
// and BEL. Upstream always emits links with BEL; links copied from the input
// keep their original terminator.
interface Golden {
  name: string;
  kind: string;
  in: string;
  n: number;
  opt: string;
  out: string;
}

const decoder = new TextDecoder();
const encoder = new TextEncoder();

function writer(c: Golden): string {
  let out = '';
  const w = newWrapWriter({
    write: chunk => { out += typeof chunk === 'string' ? chunk : decoder.decode(chunk); },
  });
  if (c.opt === 'whole') {
    w.write(c.in);
  } else {
    const bytes = encoder.encode(c.in);
    for (let k = 0; k < bytes.length; k += c.n) w.write(bytes.slice(k, k + c.n));
  }
  w.close();
  return out;
}

function hyperlinkStyle(c: Golden): string {
  const base = () => newStyle().hyperlink('https://example.com');
  switch (c.opt) {
    case 'plain': return base().render(c.in);
    case 'params': return newStyle().hyperlink('https://example.com', 'id=1').render(c.in);
    case 'width': return base().width(c.n).render(c.in);
    case 'bold-width': return newStyle().hyperlink('https://example.com', 'id=1').bold(true).width(c.n).render(c.in);
    case 'pad-center': return base().width(c.n).padding(0, 1).align(Center).render(c.in);
    case 'maxwidth': return base().maxWidth(c.n).render(c.in);
    case 'border-maxwidth': return base().border(normalBorder()).width(c.n + 2).maxWidth(c.n).render(c.in);
    case 'canvas': return newCompositor(newLayer(base().render(c.in))).render();
  }
  throw new Error(`unknown hyperlink option ${c.opt}`);
}

function run(c: Golden): string {
  switch (c.kind) {
    case 'wrap': return wrap(c.in, c.n, '');
    case 'style': return c.opt === 'width'
      ? newStyle().width(c.n).render(c.in)
      : newStyle().maxWidth(c.n).render(c.in);
    case 'truncate': return truncate(c.in, c.n);
    case 'writer': return writer(c);
    case 'ranges': return styleRanges(c.in, newRange(2, 6, newStyle().bold(true)));
    case 'canvas': return newCompositor(newLayer(c.in)).render();
    case 'hyperlink': return hyperlinkStyle(c);
    case 'sethyperlink': return c.opt ? setHyperlink(c.in, c.opt) : setHyperlink(c.in);
    case 'resethyperlink': return resetHyperlink();
  }
  throw new Error(`unknown kind ${c.kind}`);
}

describe('OSC 8 hyperlink parity with lipgloss v2.0.6 / x/ansi v0.11.8', () => {
  for (const c of goldens as Golden[]) {
    it(`${c.kind}${c.opt ? `/${c.opt}` : ''} ${c.name} n=${c.n}`, () => {
      expect(run(c)).toBe(c.out);
    });
  }

  it('truncate keeps a BEL-terminated closing sequence instead of emitting ESC \\', () => {
    const input = '\x1b]8;;http://a.b\x07linked\x1b]8;;\x07';
    expect(truncate(input, 2)).toBe('\x1b]8;;http://a.b\x07li\x1b]8;;\x07');
  });
});
