import { describe, expect, it } from 'bun:test';
import { Center, Right, newStyle, wrap } from '../src/index.js';
import goldens from './fixtures/wrap-whitespace-v2.0.6.json';

// Goldens generated by a real Go program against charm.land/lipgloss/v2@v2.0.6
// (lipgloss.Wrap and NewStyle().Width(w)...Render). They pin upstream's
// whitespace handling: leading indentation, tabs, and spaces at wrap points.
interface Golden {
  name: string;
  kind: 'wrap' | 'style';
  in: string;
  w: number;
  opt: string;
  out: string;
}

function render(c: Golden): string {
  if (c.kind === 'wrap') return wrap(c.in, c.w, '');
  let s = newStyle().width(c.w);
  switch (c.opt) {
    case 'pad': s = s.padding(0, 1); break;
    case 'center': s = s.align(Center); break;
    case 'right': s = s.align(Right); break;
    case 'tab2': s = s.tabWidth(2); break;
    case 'tabkeep': s = s.tabWidth(-1); break;
  }
  return s.render(c.in);
}

describe('wrap whitespace parity with lipgloss v2.0.6', () => {
  for (const c of goldens as Golden[]) {
    it(`${c.kind}${c.opt ? `/${c.opt}` : ''} ${c.name} w=${c.w}`, () => {
      expect(render(c)).toBe(c.out);
    });
  }

  it('preserves leading indentation when width is set (bubbles viewport regression)', () => {
    expect(newStyle().width(12).render('  indented\n    more')).toBe('  indented  \n    more    ');
  });
});
